module.exports = {
  department: 'Cabin Crew',
  mcq: [
    {
      question: 'Which of these are mentioned as briefing content that Flight Dispatchers cover? (for Cabin Crew only)',
      options: [
        'Departure and Arrival Airport',
        'Classes offered on the flight',
        "The pilot's flight minutes",
        "The aircraft's ground crew vehicles types",
        'The exact number of passengers pre-booked in each class',
        'Which cabin crew member is assigned to which class',
      ],
      correct: [0, 1],
      points: 2,
    },
    {
      question: 'According to the in-flight service script, what should you do during flight service?',
      options: [
        'Skip confirming the order and just guess based on class',
        'Ask for payment before taking their order',
        'Ask if they\'d like anything else after serving their order',
        'Serve every passenger the same preset meal without asking',
        'Wait for passengers to flag you down before offering service',
        'Ask passengers what they\'d like to eat or drink',
      ],
      correct: [2, 5],
      points: 2,
    },
    {
      question: 'What to ask passengers during check-in before proceeding the boarding pass?',
      options: [
        'Luggage, Food, Seating, Class and Identification',
        'Destination, Identification, Class, Boarding pass type and Luggage',
        'Destination, Favourite food, Seating type, Boarding Pass and Drinks',
        'Hot towel, Gate, Airport, Passport and Boarding Pass',
        'Destination, Class, Job, Identification and Luggage',
        'Nothing to ask them just tell them to proceed to boarding gate',
      ],
      correct: [1],
      points: 2,
    },
    {
      question: "How should you serve a World Business Class passenger before departure?",
      options: [
        'Offer them a hot towel and direct them to the Premium Lounge',
        'Serve them the same as Economy Class passengers',
        'Ask them to wait in the boarding area with everyone else',
        'Skip pre-flight service entirely for Business Class',
        'Offer them a hot towel, but have them remain at the gate rather than the Premium Lounge',
        'Direct them to the Premium Lounge, but skip the hot towel since that\'s Royal-Class-only',
      ],
      correct: [0],
      points: 2,
    },
    {
      question: 'After completing in-flight service for all passengers, what should you do?',
      options: [
        'Wait about 2 minutes to extend the flight time, then notify the captain that service has finished',
        'Notify the captain immediately, then wait 2 minutes before starting descent',
        'Wait about 2 minutes, then begin deboarding announcement',
        'Start service again from the first passenger to fill the extra time',
        'Wait about 5 minutes, then notify the captain',
        'Notify the captain that service has finished, with no waiting period required',
      ],
      correct: [0],
      points: 2,
    },
    {
      question: 'A passenger skipped check-in. What should you do?',
      options: [
        'Contact them for going back to check-in',
        'Ignore them',
        'Shout at them go back to gate',
        'Kick him out of the game',
        'Notify the Flight Dispatcher about him',
        'Let them skipped and continue the flight',
      ],
      correct: [0, 4],
      points: 2,
    },
  ],
  writtenQuestions: [
    {
      id: 7,
      question: 'A passenger orders chicken, then another passenger suddenly asks for beef. In that situation, how would you handle the ordering without upsetting either passenger?',
      points: 3,
      guideline: 'Prioritize the passenger ordering chicken because they are first while telling the beef passenger to wait. After completing serving chicken to first passenger, come to the beef passenger, apologize about the delay and serve them what they requested.',
    },
    {
      id: 8,
      question: 'A passenger walks up to your check-in desk. Walk through, step-by-step, exactly what you\'d say and ask them, from greeting through handing them their boarding pass.',
      points: 3,
      guideline: 'It is the entire dialogue of check-in so grade based on that. If they are wrong in any step (e.g: Asking destination) -> minus them 0.5pts',
    },
    {
      id: 9,
      question: 'What are the main things we should ask the passenger during the flight service?',
      points: 3,
      guideline: 'Welcoming them to the in-flight service of the airline (1pts). Request the passenger what they want to eat/ drink on flight (1pts). After completing serving them ask them any additional food and continue it (1pts)',
    },
    {
      id: 10,
      question: 'A passenger is being disruptive in the cabin. As a cabin crew member, what should you do?',
      points: 3,
      guideline: 'Remain calm and kindly request them to calm down (1pts). Notify the Flight Dispatcher to warn him (1pts). If he acting even worse, kick him and report him (1pts)',
    },
  ],
};
